# Generated by Django 5.2.11 on 2026-03-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_city_user_preferred_city_user_preferred_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
